version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - .:/usr/src/app
    ports:
      - 3009:3009
    depends_on:
      - db
      - web
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    depends_on:
      - db